"""add planning domain

Revision ID: 01ac61718379
Revises: 0c37bfc39de2
Create Date: 2026-08-03 23:23:51.600114+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '01ac61718379'
down_revision: str | None = '0c37bfc39de2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_cycles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('planning_type', sa.Enum('budget', 'forecast', 'rolling_forecast', 'long_range_plan', name='planning_type'), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', 'archived', name='planning_status'), server_default='draft', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_planning_cycles_valid_date_range')),
    sa.CheckConstraint('fiscal_year BETWEEN 2000 AND 2200', name=op.f('ck_planning_cycles_fiscal_year_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_planning_cycles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_cycles'))
    )
    op.create_index('ix_planning_cycles_organization_fiscal_year', 'planning_cycles', ['organization_id', 'fiscal_year'], unique=False)
    op.create_index('ix_planning_cycles_organization_status', 'planning_cycles', ['organization_id', 'status'], unique=False)
    op.create_table('scenarios',
    sa.Column('planning_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planning_cycle_id'], ['planning_cycles.id'], name=op.f('fk_scenarios_planning_cycle_id_planning_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index('ix_scenarios_planning_cycle_code', 'scenarios', ['planning_cycle_id', 'code'], unique=True)
    op.create_index('ix_scenarios_planning_cycle_default', 'scenarios', ['planning_cycle_id', 'is_default'], unique=False)
    op.create_table('budget_versions',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_budget_versions_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_versions'))
    )
    op.create_index('ix_budget_versions_scenario_active', 'budget_versions', ['scenario_id', 'is_active'], unique=False)
    op.create_index('ix_budget_versions_scenario_number', 'budget_versions', ['scenario_id', 'version_number'], unique=True)
    op.create_table('budget_lines',
    sa.Column('budget_version_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('cost_center_id', sa.Uuid(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period BETWEEN 1 AND 12', name=op.f('ck_budget_lines_period_range')),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_versions.id'], name=op.f('fk_budget_lines_budget_version_id_budget_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_lines'))
    )
    op.create_index('ix_budget_lines_version_dimensions', 'budget_lines', ['budget_version_id', 'account_id', 'department_id', 'cost_center_id'], unique=False)
    op.create_index('ix_budget_lines_version_period', 'budget_lines', ['budget_version_id', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_lines_version_period', table_name='budget_lines')
    op.drop_index('ix_budget_lines_version_dimensions', table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index('ix_budget_versions_scenario_number', table_name='budget_versions')
    op.drop_index('ix_budget_versions_scenario_active', table_name='budget_versions')
    op.drop_table('budget_versions')
    op.drop_index('ix_scenarios_planning_cycle_default', table_name='scenarios')
    op.drop_index('ix_scenarios_planning_cycle_code', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('ix_planning_cycles_organization_status', table_name='planning_cycles')
    op.drop_index('ix_planning_cycles_organization_fiscal_year', table_name='planning_cycles')
    op.drop_table('planning_cycles')
    sa.Enum(name="planning_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="planning_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
